apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  labels:
    app: mysql
data:
  master.cnf: |
    # Apply this config only on the master.
    [mysqld]
    binlog-format=ROW
    log-bin
  slave.cnf: |
    # Apply this config only on slaves.
    [mysqld]
    binlog-format=ROW
    super-read-only
    innodb_flush_log_at_trx_commit=0